In [1]:
from d2l import mxnet as d2l
from mxnet import gluon, np, npx
from mxnet.gluon import nn
import math
npx.set_np()

In [8]:
max_degree = 20
n_train, n_test = 100, 100
true_w = np.zeros(max_degree)
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])

features = np.random.normal(size=(n_train + n_test, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(max_degree).reshape(1, -1))
for i in range(max_degree):
    poly_features[:, i] /= math.gamma(i + 1)
labels = np.dot(poly_features, true_w)
labels += np.random.normal(scale=0.1, size=labels.shape)

In [9]:
poly_features.shape, features.shape, labels.shape

((200, 20), (200, 1), (200,))

In [12]:
features[:2], poly_features[:2, :], labels[:2]

(array([[1.032016 ],
        [1.0443201]]),
 array([[1.0000000e+00, 1.0320160e+00, 5.3252858e-01, 1.8319267e-01,
         4.7264442e-02, 9.7555332e-03, 1.6779777e-03, 2.4738570e-04,
         3.1913252e-05, 3.6594431e-06, 3.7766040e-07, 3.5431960e-08,
         3.0471961e-09, 2.4190425e-10, 1.7832076e-11, 1.2268658e-12,
         7.9134073e-14, 4.8039791e-15, 2.7543240e-16, 1.4960561e-17],
        [1.0000000e+00, 1.0443201e+00, 5.4530227e-01, 1.8982337e-01,
         4.9559090e-02, 1.0351110e-02, 1.8016454e-03, 2.6878493e-04,
         3.5087192e-05, 4.0713621e-06, 4.2518053e-07, 4.0365872e-08,
         3.5129075e-09, 2.8219999e-10, 2.1050509e-11, 1.4655646e-12,
         9.5657416e-14, 5.8762923e-15, 3.4092944e-16, 1.8738918e-17]]),
 array([5.3473606, 5.396351 ]))